(   START_STATE,

    INSTAGRAM_STATE,
    INSTAGRAM_DOWNLOAD_STATE,

    MUSIC_STATE,
    MUSIC_SPOTIFY_STATE,

    PINTEREST_STATE,

    YOUTUBE_STATE,
    YOUTUBE_DOWNLOAD_STATE,
    YOUTUBE_MP3_STATE,
    
    AI_STATE,
    AI_CHAT_STATE,
    AI_TTI_STATE
) = range(12)